global:
  scrape_interval: 5s
  evaluation_interval: 5s
  # scrape_timeout: 10s

rule_files:
#  - alert.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'spring-boot-app'
    metrics_path: '/manage/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
